blues/note-c

README.md
Fixing broken links in README to 
- note-arduino
- note-python
- note-go
per customer request: https://secure.helpscout.net/conversation/1420777100/93?folderId=4096820
There was a syntax error using reference links.  Should be using [] not ()
=> Fixes links to other note-* repositories in README

n_helpers.c
comparison between signed and unsigned integers
=> fix: address compiler warning

n_request.c, note.h
I added this function to allow the Truenote host to retry certain critical requests - I'm submitting a draft PR for feedback as to whether you think this is the right approach, before I update the rest of the truenote firmware.
=> Add NoteRequestWithRetry to retry requests until success or timeout

n_helpers.c
Functions declared using K&R syntax, the parameters used when the function is called must match the required data types in the function definition
This was required to get note-c to compile with clang.
https://en.cppreference.com/w/c/language/function_declaration
=> Fixes call to JATON missing typecast (const char*)

n_request.c
NoteRequestResponseWithRetry will free rsp but still return rsp in the case when NoteTransaction returns an error and expiresMs is reached. The caller then tries to free rsp again which results in an error.
This change makes sure to set rsp to NULL whenever it is deleted to prevent this.
As @russelldeguzman pointed out, this also affects NoteRequestWithRetry. I've added the fix there too
=> Fix NoteRequestResponseWithRetry (Returns already freed/deleted rsp)

n_ua.c
Add Swan as separate CPU option
=> fix: STM32L4 identification

.gitignore, README.md
Also, add *.code-workspace to .gitignore (VS Code workspace files).
=> Edit README.md to fix typo referring to note-c as an Arduino library.

n_request.c
Prior to this commit, if no response was expected in NoteTransaction, responseJSON would be a garbage value. If JParse then failed, we'd get a fault when we tried to free responseJSON. The solution is to initialize responseJSON to NULL.
=> Initialize responseJSON to NULL in NoteTransaction.

.github/actions/run_unit_tests/Dockerfile, .github/actions/run_unit_tests/action.yml, .github/workflows/ci.yml, tests/scripts/run_unit_tests.sh
~~I opted not to Dockerize this, in contrast to what's been done in note-arduino. The build already runs in a GitHub-provisioned VM, so the addition of a container inside that seems like overkill.~~
Zak and I talked, and I decided to go the Docker/container route in the end, for a few reasons:
1) No hidden dependencies. For example, the GitHub VMs come with CMake installed, among other packages we need. With the Dockerfile, we fully enumerate our dependencies, so nothing is implied or hidden.
2) Easier for developers to run the GitHub action locally. This is mainly due to 1: the container will set up whatever dependencies it needs; we don't need to install anything up front.
3) Easier to migrate to a different CI platform if we ever outgrow GitHub actions.
One key downside is that, for …
=> Add GitHub action to run unit tests with every PR.

tests/CMakeLists.txt
Example output at the end of running `make coverage`:
```
Reading tracefile lcov.info
Summary coverage rate:
lines......: 22.5% (846 of 3755 lines)
functions..: 28.1% (84 of 299 functions)
branches...: no data found
[100%] Built target coverage
```
=> Print a coverage summary after running make coverage.

n_request.c
These functions are nearly identical to NoteRequestResponse and NoteRequestResponseWithRetry, respectively. The only difference is that they delete the Notecard's response and return a bool. This commit modifies NoteRequest to use NoteRequestResponse internally. Same thing for the retry version.
=> Simplify NoteRequest and NoteRequestWithRetry.

.github/workflows/ci.yml, scripts/run_astyle.sh
The script now requires that there be no local changes before running and will return a non-zero value if astyle makes any new formatting changes.
=> Simplify run_astyle.sh by removing the --check option.

CMakeLists.txt, n_cjson_helpers.c, n_helpers.c, n_i2c.c, n_serial.c, test/CMakeLists.txt, test/src/NoteDebug_test.cpp, test/src/NotePrint_test.cpp, test/src/NotePrintln_test.cpp, test/src/NoteSerialHooks_test.cpp, test/src/NoteSetFn_test.cpp, test/src/NoteTransactionHooks_test.cpp, test/src/i2cNoteReset_test.cpp, test/src/i2cNoteTransaction_test.cpp, test/src/serialNoteReset_test.cpp, test/src/serialNoteTransaction_test.cpp
- Fix some typos in n_cjson_helpers.c Doxygen comments.
- Check return value of _SerialReset in retry loop of serialNoteReset.
- Exclude third party code (e.g. n_md5.c) from coverage report.
- Remove unnecessary "inLog" code from NotePrint.
- Get rid of the need for some casting in i2cNoteReset and serialNoteTransaction.
- Add new unit tests for serialNoteTransaction, serialNoteReset, NoteSetFn, NoteDebug, NoteTransaction hooks, NoteSerial hooks, NotePrint, and NotePrintln.
=> Add more unit tests and other cleanups.

n_helpers.c
The payload was being added to the sleep request with JCreateStringValue instead of JCreateStringReference. If the sleep fails and code keeps executing on the host, NoteRequest will JDelete the request and attempt to free the payload, which can lead to an invalid free (e.g. payload is on stack).
=> Fix bug in NoteSleep.

n_cjson_helpers.c
IAR was complaining that jumping to the later cases bypassed the init of vlen and value
=> Fix warning about scope of vars declared within switch case

.github/actions/run_unit_tests/Dockerfile, CMakeLists.txt, scripts/run_unit_tests.sh, test/src/NoteGetEnv_test.cpp
Turn it on for the GitHub action that runs unit tests. Also, resolve a memory leak in NoteGetEnv_test.cpp.
=> Add optional memory checking with valgrind.

n_helpers.c
See 571894e900d55c3674c3e272e373f1faff8c19a3 for similar fixes.
=> Fix millisecond rollover bug in NoteDebugSyncStatus.

CMakeLists.txt, n_helpers.c, note.h, test/CMakeLists.txt
If the TEST macro is defined, STATIC is defined to nothing. If TEST isn't defined, STATIC is defined to static.
=> Add a STATIC macro for static functions.

.devcontainer/devcontainer.json, .github/actions/run_unit_tests/Dockerfile, n_ua.c
```none
warning: data definition has no type or storage class
warning: type defaults to 'int' in declaration of 'n_cpu_name' [-Wimplicit-int]
error: conflicting types for 'n_cpu_name'; have 'int'
```
Variables may only be declared at global scope, not assigned.
Fix adds type prefix to change from assignment to declaration.
=> fix: assignment error

CMakeLists.txt, scripts/run_unit_tests.sh, test/CMakeLists.txt
This prevents collisions with other CMake options when, for example, note-c is included in another CMake project via add_subdirectory.
=> Prefix CMake options with NOTE_C.

n_lib.h
This change was already made in note-go. We're rolling it out to the other SDKs, now.
=> Extend transaction timeout to 30 seconds from 10.

CMakeLists.txt, scripts/run_unit_tests.sh
Instead, force note-c to always be built as a shared library. Then, when the test binaries are built, the mocks for any note-c functions supersede any of their "real" counterparts in the shared library. This means that the mock will always be called and not the "real" function. See: https://stackoverflow.com/a/4434602/3646689
The reason we were weakening the mocked symbols in the first place is that you have to if you build note-c as a static lib. If you don't, the mocks will cause multiple definition errors. If you weaken the function being mocked, though, the mock is able to override the "real" function. Forcing note-c to be a shared lib is an easier solution.
=> Don't bother weakening mocked symbols for unit tests.

test/CMakeLists.txt
Prior to this change, coverage was cumulative across `make coverage` runs. For example, you'd see a line report that it was executed N times instead of just once, where N is the number of times `make coverage` was run.
=> Zero the coverage counters before every coverage run.

n_request.c
Intellisense looks for the `@param` marker to identify API parameters. Added missing `@param` to parameters to fix intellisense, along with any other auto-generated documentation.
=> Update API comments in n_request.c

.github/actions/run_unit_tests/Dockerfile, .vscode/extensions.json, n_cjson.c, n_hooks.c, n_lib.h, n_md5.c, n_request.c, note.h, test/CMakeLists.txt, test/include/test_static.h, test/src/NoteTransaction_test.cpp, test/src/crcAdd_test.cpp, test/src/crcError_test.cpp
The feature, which works only for 'requests' and not 'commands', works like this:
- every request's JSON is tagged with an additional field "crc" containing a sequence number and crc32 of the request
- notecard firmware prior to the new firmware ignores the extra json field
- the new firmware, as it sees this field, verifies the crc and sends an {io} error response back to the host if it doesn't match
- if the crc is present AND it matches, the firmware then attaches an analogous crc to the response back to note-c, containing the exact same sequence number that it received on the request
- note-c, when it receives the response, verifies this crc
- in note-c, if the sequence number is ever unexpected or the crc mismatches or it gets an {io} error, it automatically retries up to 10 times …
=> feat: add automatic crc support, supported by notecard firmware as of 2023-06-10

test/src/crcError_test.cpp
Specifically, add a test that makes sure \r\n is stripped properly.
=> Add additional crcError testing.

n_serial.c
A NEWLINE, and only a NEWLINE, must be sent to reset the connection with the Notecard, because there are some versions of the Notecard firmware will not respond to `\r\n` after communicating over I2C.
=> fix: serialNoteReset()

n_helpers.c, n_i2c.c, n_serial.c, test/src/NoteBinaryStoreReceive_test.cpp, test/src/i2cNoteReset_test.cpp
ensure reset will consume all available bytes,
regardless of the amount. Previously, the 5-second
timeout would prevent reset from consuming large
outstanding, binary data payloads.
=> Zak mem drain

n_lib.h, n_request.c
Also, make them all conform to the same style.
This is a step toward generating the API docs for note-c. I'll tackle the other source files next, and eventually will come up with a scheme for generating and publishing the docs somewhere.
=> Improve Doxygen comments in n_request.c.

n_ftoa.c
Prior to this commit, we'd get some invalid JSON back in this case. Now we'll get 0 back.
=> Fix JNtoA in the case where the number won't fit in the provided buffer.

scripts/git_hooks/pre-push, scripts/run_astyle.sh
Developers can install these hook in .git/hooks/ in their local note-c repo. The pre-push hook runs the unit tests (without valgrind, because it's slow), builds the Doxygen docs, and runs astyle. If any of those fail, the hook fails, and the push won't go through. This should save us some churn on CI builds on GitHub.
=> Add a scripts/git_hooks directory with a pre-push hook.

n_helpers.c, n_hooks.c, n_lib.h, n_ua.c, test/src/NoteBinaryStoreReceive_test.cpp, test/src/NoteBinaryStoreTransmit_test.cpp, test/src/NoteDebug_test.cpp, test/src/NotePrint_test.cpp, test/src/NoteRequestResponseJSON_test.cpp, test/src/NoteReset_test.cpp, test/src/NoteSerialHooks_test.cpp, test/src/NoteSetFnI2C_test.cpp, test/src/NoteSetFnMutex_test.cpp, test/src/NoteSetFnNoteMutex_test.cpp, test/src/NoteSetFnSerial_test.cpp, test/src/NoteTransactionHooks_test.cpp, test/src/NoteTransaction_test.cpp, test/src/i2cChunkedReceive_test.cpp, test/src/i2cChunkedTransmit_test.cpp, test/src/i2cNoteQueryLength_test.cpp, test/src/i2cNoteReset_test.cpp, test/src/serialChunkedReceive_test.cpp, test/src/serialChunkedTransmit_test.cpp, test/src/serialNoteReset_test.cpp, test/src/serialNoteTransaction_test.cpp
All internal/private functions in note-c should begin with a lowercase letter.
See https://github.com/blues/note-c/pull/99#discussion_r1324923027.
=> Standardize private function naming.

docs/api_reference.rst, n_cjson.c, n_cjson.h
This limit is controlled with the macro `N_CJSON_NESTING_LIMIT`, which the user can override. This commit adds Doxygen documentation for it and includes it in the note-c docs site. The documentation references `JParse`, so I added documentation for that, too.
=> Reduce the cJSON object nesting limit from 1000 to 100 and document the macro.

.github/workflows/notecard-binary-tests.yml, scripts/run_tunnelmole.sh, test/hitl/card.binary/test/test_card_binary.cpp
These were disabled because there was a Notecard firmware bug that would drop a pair of bytes every ~1600 bytes of a binary transmit to the Notecard. Fixed with https://github.com/blues/notecard/commit/cb348dd496ae6f38990d8fdfa6d68478d49a4d1b.
=> Enable some previously disabled card.binary HIL tests.

.github/workflows/ci.yml, CMakeLists.txt, n_cjson.c, scripts/check_libc_dependencies.sh, test/CMakeLists.txt, test/include/test_static.h, test/src/JPrintUnformatted_test.cpp, test/src/Jtolower_test.cpp
See commit messages for more details.
=> Limit scope of libc usage in note-c.

scripts/run_tunnelmole.sh, test/hitl/card.binary/test/test_card_binary.cpp
- Don't put the MD5 server URL in the log output. We want to keep that private.
- Dynamically computed binary store size based on the MCU being used by the
Notecard (i.e. r5 vs. u5).
- Change timeout in waitForNotecardConnected to 5 minutes instead of 300 ms,
which I believe was a mistake.
=> Make some tweaks to HIL testing.

docs/index.rst
We just changed our main site from blues.io to blues.com.
=> Chore: update index.rst: blues.io => blues.com

.github/workflows/ci.yml, CMakeLists.txt, n_lib.h, n_request.c, scripts/run_unit_tests.sh, test/src/NoteTransaction_test.cpp, test/src/NoteUserAgent_test.cpp, test/src/crcAdd_test.cpp, test/src/crcError_test.cpp
Prior to this commit, NOTE_LOWMEM was fundamentally broken because it would cause our core transaction logic to never return a response from the Notecard. This commit fixes that and the relevant unit tests. There were some other unit tests that were broken for different reasons. For example, the CRC tests should never run with NOTE_LOWMEM defined because all the CRC logic is cut out.
Additionally, the n_ua.c is empty if NOTE_LOWMEM is defined. This implies that NOTE_DISABLE_USER_AGENT should be defined if NOTE_LOWMEM is defined, so I added that logic to n_lib.h.
This commit also adds a CI build that runs the unit tests with NOTE_LOWMEM defined.
=> Fix NOTE_LOWMEM.

n_hooks.c, n_i2c.c, n_lib.h, n_request.c, n_serial.c, note.h, test/include/test_static.h, test/include/time_mocks.h, test/src/NoteBinaryStoreReceive_test.cpp, test/src/NoteDebugSyncStatus_test.cpp, test/src/NoteRequestResponseJSON_test.cpp, test/src/NoteRequestWithRetry_test.cpp, test/src/NoteSetFnI2C_test.cpp, test/src/NoteSetFnSerial_test.cpp, test/src/NoteTimeSet_test.cpp, test/src/NoteTime_test.cpp, test/src/NoteTransaction_test.cpp, test/src/i2cChunkedReceive_test.cpp, test/src/i2cNoteQueryLength_test.cpp, test/src/i2cNoteReset_test.cpp, test/src/i2cNoteTransaction_test.cpp, test/src/serialChunkedReceive_test.cpp, test/src/serialNoteReset_test.cpp, test/src/serialNoteTransaction_test.cpp
This commit resolves a couple problems.
First, it changes the return type of NoteGetMs. NoteGetMs is simply a wrapper around the user-supplied millisecond timer hook. The prototype for this hook specifies that it should return a uint32_t yet NoteGetMs's return type is long unsigned int. This commit changes the return type of NoteGetMs to uint32_t.
Second, there are many places in the code where we are comparing and assigning millisecond timer values (i.e. gotten via NoteGetMs) to size_t variables. This is a bug. On some platforms (e.g. the Arduino Uno), size_t is 16 bits, so assigning one of these 32-bit millisecond timer values to a 16-bit variable can lead to undefined behavior when the timer value is larger than what can fit into 16 bits. This commit fixes all these bugs by using …
=> Fix timeout data type bugs.

n_atof.c, n_cjson.c, n_cjson.h, n_cjson_helpers.c, note.h, test/CMakeLists.txt, test/src/JItoA_test.cpp, test/src/JSON_number_handling_test.cpp
- Get rid of CJSON_NO_CLIB and its associated code paths, per Ray's request.
- Change the type of the J object's valueint member. It should be int32_t if NOTE_LOWMEM and int64_t otherwise. Capture this in a new #define for the type, JINTEGER.
- When parsing a JSON number from a JSON string, if the number is within the bounds of the JINTEGER type, convert it to an integer using JAtoI rather than simply casting valuenumber to JINTEGER, which can lose precision (e.g. for a Unix timestamp). If the number is outside the bounds of a JINTEGER, saturate, which is the same behavior as before this commit.
- When printing a JSON number, print it as an integer if possible. Otherwise, print it as floating point.
- Fix an issue where JItoA would fail to convert the minimum long int value (i.e. …
=> Improve cJSON number handling.

docs/api_reference.rst, n_cjson.c
`JPrintUnformatted` is particularly important because it's what allows the user to convert a `J *` to a string. We already document `JParse`, which does the reverse, so we should document `JPrintUnformatted`, too.
Because the function dynamically allocates memory, we need to tell the user how to free it. So, I also added documentation for `JFree`. And while I was at it, I added documentation for `JMalloc`.
=> Add documentation for a few additional cJSON functions.

CMakeLists.txt, n_atof.c, n_cjson_helpers.c, n_helpers.c, n_hooks.c, n_i2c.c, n_lib.h, n_request.c, n_ua.c, note.h, scripts/run_unit_tests.sh, test/src/JAtoI_test.cpp, test/src/JItoA_test.cpp, test/src/JSON_number_handling_test.cpp, test/src/NoteGetLocation_test.cpp, test/src/NoteGetStatus_test.cpp, test/src/NoteTransaction_test.cpp, test/src/NoteUserAgent_test.cpp, test/src/crcAdd_test.cpp, test/src/crcError_test.cpp
Make more fixes to number handling and NOTE_C_LOW_MEM code.
- Remove #ifdef ERRDBG guard in i2cNoteReset. This was causing us to not call
_I2CReset when we should have been.
- Make JTIME a typedef for JUINTEGER.
- Fix run_unit_tests.sh script so that it actually runs the tests with
NOTE_C_LOW_MEM defined.
- Use JAddIntToObject to add Unix timestamps to J objects in unit tests. This is
necessary to avoid loss of precision when using JAddNumberToObject.
---
Improve JSON number handling (continued).
- Change NOTE_LOWMEM to NOTE_C_LOW_MEM. If NOTE_C_LOW_MEM is defined, the old
macro NOTE_LOWMEM is automatically defined. Same for NOTE_FLOAT, which was also
removed.
- Change JItoA, JAtoI, NoteSetEnvDefaultInt, and NoteGetEnvInt to use JINTEGER
instead of long int.
- Make JINTEGER a typedef for …
=> Improve JSON number handling (continued).

.github/workflows/ci.yml, CMakeLists.txt, n_atof.c, n_ftoa.c, note.h, scripts/run_unit_tests.sh, test/CMakeLists.txt, test/src/JAtoN_test.cpp, test/src/JNtoA_test.cpp, test/src/JSON_number_handling_test.cpp
- Incorporate Ray's improvements to n_ftoa.c and n_atof.c that allow us to support larger exponents.
- Add JAtoN and JNtoA unit tests to test these improvements.
- If NOTE_C_LOW_MEM is defined, define JNUMBER to float. On truly low memory platforms, this likely does nothing, because those platforms often map double and float to the same underlying type (which is single-precision). However, when running the unit tests on a CPU with double-precision floating point support, this allows us to deliberately run the unit tests with JNUMBER set to single-precision. Doing this broke a couple test cases in JSON_number_handling_test.cpp, which I've fixed here.
=> Make more JSON number handling improvements.

scripts/check_libc_dependencies.sh
The code path that used this function was recently removed, so we no longer need to whitelist it in the script that checks for libc dependencies.
=> Remove strtod from allowed libc functions.

n_i2c.c, n_serial.c, note.h
ERRDBG is a macro that's used to conditionally compile in various error logs. It's not used consistently, and we also already support log levels and NOTE_NODEBUG, which are more than enough to control the desired level of logging at compile-time.
=> Remove ERRDBG.

n_request.c, test/hitl/card.binary/lib/notecard_binary/NotecardBinary.h, test/hitl/card.binary/lib/notecard_binary/NotecardComms.cpp, test/hitl/card.binary/lib/notecard_binary/NotecardComms.h, test/hitl/card.binary/test/test_card_binary.cpp, test/src/NoteRequestResponseJSON_test.cpp
Previously we had allowed strings to be sent via `note-c` without a newline-terminator.
Subsequently, we decided this was undefined behavior that should not be supported.
This caused a regression in downstream testing, and we have restored the original
behavior (although undefined by the Notecard communication specification).
=> bug: Undefined behavior regression

.github/workflows/notecard-binary-tests.yml, scripts/run_md5srv.sh, scripts/run_tunnelmole.sh
- Remove the unused localtunnel code. If we ever need to switch to localtunne
from tunnelmole, we can pull it out of the git history.
- Remove usage of third party action pyTooling/Actions/with-post-step. Instead,
to run cleanup steps, use the `if: always()` construct.
- Remove usage of third party action JarvusInnovations/background-action@v1.
The scripts we need to run in the background can simply be launched in the
background using & syntax.
- Refactor a bunch of conditional logic that was hard to read. Instead of using
if statements, we were chaining together a bunch of different Bash statements
using logical operators. Using if statements is simpler to read and understand
what exactly is being checked.
- Refactor run_tunnelmole.sh.
=> Refactor card.binary HIL GitHub workflow.

n_request.c
First, the method NotecardRequestResponseJSON had a very bad behavior when there was an I/O error, returning NULL instead of a JSON object that would indicate the source of the error.
second, for both standard NotecardRequestResponse as well as NotecardRequestResponseJSON, if there is an error the 'error object' should include the "id" field of the requestor, for tracking of requests/responses.
=> fix: two fixes to improve performance of notepod

n_cjson.c, n_cjson.h
We added this function to the note-c copy used in the NOTE-LORA firmware with NF-473.
We aim to keep the note-c used in the firmware the same as the upstream note-c we distribute as an SDK, so we need to bring this function over.
=> TS-513: Add JPrintPreallocated to note-c.

test/CMakeLists.txt, test/src/NoteResponseError_test.cpp
Check both positive and negative case
=> adds test case for NoteResponseError macro

.github/workflows/notecard-binary-tests.yml, test/hitl/card.binary/platformio.ini
- Hardcode Notestation to los-angeles-notestation-1. This one's known to be set up for running these tests. I have work in progress to make it so this doesn't need to be hardcoded (i.e. the Notestation client can discover which stations can run these tests), but it's not finished, yet.
- Make sure to kill the Notestation client in the GitHub Actions workflow when done with the Notestation.
- Move the `file .pio/build/debug/firmware.elf` gdb command earlier in the custom upload command for PlatformIO. This just gets rid of some warnings I was seeing in the log. No functional difference.
- Change test_port to /tmp/ns_mcu_usb from /tmp/mcu_usb. The former is the new default path for the MCU USB device with the latest Notestation client.
=> NF-613: Fix card.binary HIL tests.

n_cjson.c
- use comments to explain why these warnings are not valid
- suppress possible `NULL` pointer deference from `cppcheck`
=> fix: static analysis issues

.github/workflows/notecard-binary-tests.yml
Other changes:
- Update workflow to use new notestation CLI.
- Add AWS credentials step to workflow. Needed in order to download Notecard firmware from S3.
- Run the tests nightly instead of weekly.
=> NF-1163: Update Notecard firmware nightly for card.binary HIL tests.

test/hitl/card.binary/lib/notecard_binary/NotecardComms.cpp
In this PR, we removed code that automatically called card.aux.serial with ms
and max parameters to add flow control for AUX serial comms in note-arduino:
https://github.com/blues/note-arduino/pull/141 It turns out these tests were
relying on that behavior in order to not have Notecard responses over AUX
serial wind up corrupted. This corruption was manifesting as CRC errors on the
responses. I saw with a logic analyzer that the Notecard was sending the correct
response, but that note-c/the Swan was not receiving it correctly. So the fix
is to restore the card.aux.serial request with the old ms and max parameters by
adding it to the test.
=> TS-713: Fix CRC errors over AUX serial in card.binary HIL tests.
